Lab5/Models/ErrorViewModel.cs
using System;

namespace bgkol_lab5.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Lab5/Models/Lab1DataModel.cs
namespace bgkol_lab5.Models
{
	public class Lab1DataModel
	{
		public string InputNumber { get; set; }
		public string ErrorValue { get; set; }
		public string Response { get; set; }
		public string Calculated { get; set; }
	}
}

Lab5/Models/Lab2DataModel.cs
namespace bgkol_lab5.Models
{
	public class Lab2DataModel
	{
		public string FirstLine { get; set; }
		public string SecondLine { get; set; }
		public string ThirdLine { get; set; }
		public string ErrorValue { get; set; }
		public string Response { get; set; }
		public string Calculated { get; set; }
	}
}

Lab5/Models/Lab3DataModel.cs
namespace bgkol_lab5.Models
{
	public class Lab3DataModel
	{
		public string FirstLine { get; set; }
		public string SecondLine { get; set; }
		public string ThirdLine { get; set; }
		public string ErrorValue { get; set; }
		public string Response { get; set; }
		public string Calculated { get; set; }
	}
}

Lab5/Models/UserProfileModel.cs
namespace bgkol_lab5.Models
{
	public class UserProfileModel
	{
		public string Email { get; set; }
		public string UserName { get; set; }
		public string EmailVerified { get; set; }

	}
}

Lab5/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Okta.AspNetCore;
using bgkol_lab5.Models;

namespace bgkol_lab5.Controllers
{
	public class AccountController : Controller
	{
		// [Authorize(Roles = "Lab5Groups")]
		// public IActionResult EnthusiastOnly()
		// {
		//     return View();
		// }

		[HttpGet]
		public IActionResult SignIn()
		{
			if (!HttpContext.User.Identity.IsAuthenticated)
			{
				return Challenge(OktaDefaults.MvcAuthenticationScheme);
			}
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public IActionResult SignOut()
		{
			return new SignOutResult(
				new[]
				{
					OktaDefaults.MvcAuthenticationScheme,
					CookieAuthenticationDefaults.AuthenticationScheme,
				},
				new AuthenticationProperties { RedirectUri = "/Home/" });
		}

		[HttpGet]
		public IActionResult Profile()
		{
			return View(new UserProfileModel()
			{
				UserName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "name").Value.ToString(),
				Email = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "email").Value.ToString(),
				EmailVerified = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "email_verified").Value.ToString()
			});
		}
	}
}

Lab5/Controllers/HomeController.cs
using bgkol_lab5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace bgkol_lab5.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Lab5/Controllers/LabsController.cs
using bgkol_lab5.Models;
using LabsLibrary;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace bgkol_lab5.Controllers
{
	[Authorize]
	public class LabsController : Controller
	{
		private readonly ILogger<LabsController> _logger;

		public LabsController(ILogger<LabsController> logger)
		{
			_logger = logger;
		}

		public IActionResult Lab1()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Lab1(Lab1DataModel model)
		{
			var labRunner = new Lab1Runner(model.InputNumber);

			try
			{
				model.Calculated = labRunner.RunLab();
			}
			catch (ArgumentException e)
			{
				model.ErrorValue = e.Message;
			}
			catch (Exception e)
			{
				model.ErrorValue = e.Message;
			}

			return View(model);
		}

		public IActionResult Lab2()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Lab2(Lab2DataModel model)
		{
			var labRunner = new Lab2Runner(model.FirstLine, model.SecondLine, model.ThirdLine);

			try
			{
				model.Calculated = labRunner.RunLab();
			}
			catch (ArgumentException e)
			{
				model.ErrorValue = e.Message;
			}
			catch (Exception e)
			{
				model.ErrorValue = e.Message;
			}

			return View(model);
		}

		public IActionResult Lab3()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Lab3(Lab3DataModel model)
		{
			var labRunner = new Lab3Runner(model.FirstLine, model.SecondLine, model.ThirdLine);

			try
			{
				model.Calculated = labRunner.RunLab();
			}
			catch (ArgumentException e)
			{
				model.ErrorValue = e.Message;
			}
			catch (Exception e)
			{
				model.ErrorValue = e.Message;
			}

			return View(model);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Lab5/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Bohdan Kolomiychenko IPS-43</h1>
	<p>Crossplatform lab5</p>
</div>

Lab5/Views/Labs/Lab1.cshtml
@model Lab1DataModel

@{
	ViewData["Title"] = "№1";
}

<h1>@ViewData["Title"]</h1>
<text> &nbsp; &nbsp; &nbsp;</text>
<h2>Программа, которая найдет сколькими способами можно рассадить гостей так, чтобы ни один из них не сидел там, где лежала карточка с его фамилией</h2>

<text> &nbsp; &nbsp; &nbsp;</text>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="Lab1">
	<div class="form-group">
		<label for="psize">Входное число</label>
		<input type="text" class="form-control" id="amountBreeds" asp-for="InputNumber">
	</div>
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

<text> &nbsp; &nbsp; &nbsp;</text>
<text> &nbsp; &nbsp; &nbsp;</text>

@if (Model != null)
{
	<div class="container mt5">
		<div class="form-group">
			<h2 class="control-label">Результат: @(Model != null ? Model.Calculated : string.Empty)</h2>
		</div>
		@if (Model != null && !string.IsNullOrEmpty(Model.ErrorValue))
		{
			<div class="row">
				<label for="perror"></label>
				<input type="text" id="perror" value="@Model.ErrorValue">
			</div>
		}
	</div>
}

Lab5/Views/Labs/Lab2.cshtml
@model Lab2DataModel

@{
	ViewData["Title"] = "№2";
}

<h1>@ViewData["Title"]</h1>
<text> &nbsp; &nbsp; &nbsp;</text>
<h2>Программа которая выведет целое число – сумму элементов найденного прямоугольного подмассива</h2>

<text> &nbsp; &nbsp; &nbsp;</text>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="Lab2">
	<div class="form-group">
		<label for="psize">Первая линия</label>
		<input type="text" class="form-control" id="input" asp-for="FirstLine">
	</div>
	<div class="form-group">
		<label for="pdata">Вторая линия</label>
		<input type="text" class="form-control" id="input" asp-for="SecondLine">
	</div>
	<div class="form-group">
		<label for="pdata">Третья линия</label>
		<input type="text" class="form-control" id="input" asp-for="ThirdLine">
	</div>
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

<text> &nbsp; &nbsp; &nbsp;</text>
<text> &nbsp; &nbsp; &nbsp;</text>

@if (Model != null)
{
	<div class="container mt5">
		<div class="form-group">
			<h2 class="control-label">Результат: @(Model != null ? Model.Calculated : string.Empty)</h2>
		</div>
		@if (Model != null && !string.IsNullOrEmpty(Model.ErrorValue))
		{
			<div class="row">
				<label for="perror"></label>
				<input type="text" id="perror" value="@Model.ErrorValue">
			</div>
		}
	</div>
}

Lab5/Views/Labs/Lab3.cshtml
@model Lab3DataModel

@{
	ViewData["Title"] = "№3";
}

<h1>@ViewData["Title"]</h1>
<text> &nbsp; &nbsp; &nbsp;</text>
<h2>Программа для вывода искомого максимального кратчайшего расстояния</h2>

<text> &nbsp; &nbsp; &nbsp;</text>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="Lab3">
	<div class="form-group">
		<label for="psize">Первая линия</label>
		<input type="text" class="form-control" id="input" asp-for="FirstLine">
	</div>
	<div class="form-group">
		<label for="pdata">Вторая линия</label>
		<input type="text" class="form-control" id="input" asp-for="SecondLine">
	</div>
	<div class="form-group">
		<label for="pdata">Третья линия</label>
		<input type="text" class="form-control" id="input" asp-for="ThirdLine">
	</div>
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

<text> &nbsp; &nbsp; &nbsp;</text>
<text> &nbsp; &nbsp; &nbsp;</text>

@if (Model != null)
{
	<div class="container mt5">
		<div class="form-group">
			<h2 class="control-label">Результат: @(Model != null ? Model.Calculated : string.Empty)</h2>
		</div>
		@if (Model != null && !string.IsNullOrEmpty(Model.ErrorValue))
		{
			<div class="row">
				<label for="perror"></label>
				<input type="text" id="perror" value="@Model.ErrorValue">
			</div>
		}
	</div>
}

Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/iklab5.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Info</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				@if (User.Identity.IsAuthenticated)
				{
					<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
						<ul class="navbar-nav flex-grow-1">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="Lab1">Lab1</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="Lab2">Lab2</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="Lab3">Lab3</a>
							</li>
						</ul>
					</div>
				}

				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					@if (User.Identity.IsAuthenticated)
					{
						<ul class="nav navbar-nav navbar-right">
							<li><p class="navbar-text">Hello, @User.Identity.Name </p></li>
							<li><a class="nav-link" asp-controller="Account" asp-action="Profile" id="profile-button">Profile</a></li>
							<li>
								<form class="form-inline" asp-controller="Account" asp-action="SignOut" method="post">
									<button type="submit" class="nav-link btn btn-link text-dark" id="logout-button">Sign Out</button>
								</form>
							</li>
						</ul>
					}
					else
					{
						<ul class="nav navbar-nav navbar-right">
							<li><a class="nav-link" asp-controller="Account" asp-action="SignIn" id="login-button">Sign In</a></li>
						</ul>
					}
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>


